mathjax.settings:
  label: 'MathJax settings'
  type: config_object
  mapping:
    use_cdn:
      type: integer
      label: 'Use a CDN'
    cdn_url:
      type: string
      label: 'CDN URL'
    config_type:
      type: integer
      label: 'Configuration type'
    default_config_string:
      type: string
      label: 'Default configuration'
    config_string:
      type: string
      label: 'Current configuration'
    enable_for_admin:
      type: integer
      label: 'Enable on admin pages'
