<?php

/**
 * @file
 * Contains mobile_detect_twig_extensions.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_detect_twig_extensions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_detect_twig_extensions module.
    case 'help.page.mobile_detect_twig_extensions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mobile detect Twig Extensions') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function mobile_detect_twig_extensions_theme() {
  $theme = [];

  return $theme;
}
